services:
  postgres:
    image: postgres:17.5
    container_name: ${NAME_PREFIX}-postgres-${BRANCH_SUFFIX}
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGTZ=UTC
    volumes:
      - /home/salko/postgres-dev/postgres-data:/var/lib/postgresql/data
      - /home/salko/postgres-dev/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", -h "localhost", "-p", "5432"]
      interval: 30s
      timeout: 10s
      retries: 5

  nextjs:
    image: ghcr.io/mrmikoma/salko_website-nextjs-dev:${VERSION}
    container_name: ${NAME_PREFIX}-nextjs-${BRANCH_SUFFIX}
    networks:
      - internal
      - outgoing
    env_file: .env.dev
    environment:
      - PORT=${CONTAINER_PORT}
      - HOSTNAME=${HOSTNAME}
    #  - DATABASE_CONNECTION_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-${BRANCH_SUFFIX}:${POSTGRES_HOST_PORT}/${POSTGRES_DB}
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    restart: unless-stopped
    # healthcheck:
    #   test: curl --fail http://localhost:3001/ || exit 1
    #   interval: 60s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 30s
    labels:
      - traefik.enable=true
      # Route for static assets (no path prefix stripping needed)
      - traefik.http.routers.nextjs-static-${BRANCH_SUFFIX}.rule=Host(`${SITE_PREFIX}.${HOST_URL}`) && PathPrefix(`/_next/`)
      - traefik.http.routers.nextjs-static-${BRANCH_SUFFIX}.entrypoints=websecure
      - traefik.http.routers.nextjs-static-${BRANCH_SUFFIX}.tls.certresolver=cloudflare
      - traefik.http.routers.nextjs-static-${BRANCH_SUFFIX}.priority=100
      # Route for application pages (with path prefix)
      - traefik.http.routers.nextjs-${BRANCH_SUFFIX}.rule=Host(`${SITE_PREFIX}.${HOST_URL}`) && PathPrefix(`/${SITE_PREFIX}`)
      - traefik.http.routers.nextjs-${BRANCH_SUFFIX}.entrypoints=websecure
      - traefik.http.routers.nextjs-${BRANCH_SUFFIX}.tls.certresolver=cloudflare
      - traefik.http.routers.nextjs-${BRANCH_SUFFIX}.middlewares=strip-prefix-${BRANCH_SUFFIX}
      - traefik.http.routers.nextjs-${BRANCH_SUFFIX}.priority=50
      # Service and middleware definitions
      - traefik.http.services.nextjs-${BRANCH_SUFFIX}.loadbalancer.server.port=${CONTAINER_PORT}
      - traefik.http.middlewares.strip-prefix-${BRANCH_SUFFIX}.stripPrefix.prefixes='/${SITE_PREFIX}'
      # - traefik.http.services.nextjs-${BRANCH_SUFFIX}.loadbalancer.healthcheck
      # - traefik.http.services.nextjs-${BRANCH_SUFFIX}.rateLimit.burst=100
      # - traefik.http.services.nextjs-${BRANCH_SUFFIX}.rateLimit.average=50

#   whoami:
#     image: traefik/whoami
#     container_name: whoami
#     networks:
#       - outgoing
#     env_file: .env.dev
#     labels:
#       - traefik.enable=true
#       - traefik.http.routers.whoami.rule=Host(`${SITE_PREFIX}.${HOST_URL}`) && PathPrefix(`/${SITE_PREFIX}`)
#       - traefik.http.routers.whoami.entrypoints=websecure
#       - traefik.http.routers.whoami.tls.certresolver=cloudflare
#       - traefik.http.routers.whoami.middlewares=strip-prefix
#       - traefik.http.middlewares.strip-prefix.stripPrefix.prefixes='/${SITE_PREFIX}'

networks:
  internal:
    driver: bridge
  outgoing:
    external: true
    name: global_outgoing
