version: "3.8"

services:
  traefik:
    image: "traefik:v3.2"
    container_name: salko-traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mikoma114@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

  watchtower:
    image: containrrr/watchtower:v1.7.1
    container_name: salko-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    restart: always

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`salko-dev.mikoma.fi`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=myresolver
      - traefik.http.routers.whoami.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # - traefik.http.services.my-website-frontend.loadbalancer.server.port=3000
      # - traefik.http.services.my-website-frontend.loadbalancer.healthcheck
      # - traefik.http.services.my-website-frontend.rateLimit.burst=5
      # - traefik.http.services.my-website-frontend.rateLimit.period=1s

  whoamii:
    image: "traefik/whoami"
    container_name: "simple-service-2"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`salko-prod.mikoma.fi`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=myresolver
      - traefik.http.routers.whoami.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # - traefik.http.services.my-website-frontend.loadbalancer.server.port=3000
      # - traefik.http.services.my-website-frontend.loadbalancer.healthcheck
      # - traefik.http.services.my-website-frontend.rateLimit.burst=5
      # - traefik.http.services.my-website-frontend.rateLimit.period=1s
