---
- name: Harden SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: true
  with_items:
    - {regexp: '^PermitRootLogin', line: 'PermitRootLogin prohibit-password'}
    - {regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no'}
    - {regexp: '^X11Forwarding', line: 'X11Forwarding no'}
    - {regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 6'}
    - {regexp: '^#?AllowTcpForwarding', line: 'AllowTcpForwarding no'}
    - {regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding no'}
    - {regexp: '^#?AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys'}
    - {regexp: '^#?PublicKeyAuthentication', line: 'PublicKeyAuthentication yes'}
    - {regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no'}

- name: Ensure root has SSH directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Ensure users are allowed
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers root salko"
    insertafter: EOF

- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted
