---
- name: Harden SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^X11Forwarding', line: 'X11Forwarding no' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 2' }
    - { regexp: '^#?AllowTcpForwarding', line: 'AllowTcpForwarding no' }
    - { regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding no' }
    - { regexp: '^#?AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
    - { regexp: '^#?PublicKeyAuthentication', line: 'PublicKeyAuthentication yes' }

- name: Ensure root has SSH directory
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Add GitHub public keys to root authorized_keys
  get_url:
    url: "https://github.com/{{ github_username }}.keys"
    dest: /root/.ssh/authorized_keys
    mode: '0600'

- name: Ensure root is allowed
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers root"
    insertafter: EOF

- name: Restart SSH
  systemd:
    name: ssh
    state: restarted
