---
- name: Update and upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - postgresql-client-common
    state: present
    update_cache: true

- name: Create salko admin
  ansible.builtin.user:
    name: salko
    shell: /bin/bash
    create_home: true
    home: /home/salko
    password: "{{ lookup('env', 'SALKO_USER_PW_512') }}"
    groups: sudo
    append: true
    state: present

- name: Create deployment directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: "{{ item.owner | default('salko') }}"
    group: "{{ item.group | default('salko') }}"
  loop:
    - { path: /home/salko/traefik }
    - { path: /home/salko/postgres }
    - { path: /home/salko/postgres-dev }
    - { path: /home/salko/nextjs }

- name: Ensure acme.json file exists for Traefik
  ansible.builtin.file:
    path: /home/salko/traefik/acme.json
    state: touch
    mode: "0600"
    owner: salko
    group: salko

- name: Ensure .ssh directory exists for salko
  ansible.builtin.file:
    path: /home/salko/.ssh
    state: directory
    mode: "0700"
    owner: salko
    group: salko

- name: Copy repository secret key to authorized keys
  ansible.builtin.copy:
    dest: /home/salko/.ssh/authorized_keys
    content: "{{ lookup('env', 'VPS_PUBLIC_KEY') }}\n"
    mode: "0600"
    owner: salko
    group: salko
    backup: true

- name: Add GitHub public keys to salko authorized keys
  ansible.builtin.get_url:
    url: "https://github.com/{{ github_username }}.keys"
    dest: /home/salko/.ssh/salko_authorized_keys
    mode: "0600"
    owner: salko
    group: salko

- name: Append GitHub public keys to salko authorized keys
  ansible.builtin.shell: |
    cat /home/salko/.ssh/salko_authorized_keys >> /home/salko/.ssh/authorized_keys
  args:
    executable: /bin/bash
  changed_when: false

- name: Remove temporary authorized keys file
  ansible.builtin.file:
    path: /home/salko/.ssh/salko_authorized_keys
    state: absent
