name: Deploy "dev" branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        default: "latest"
        type: string
      branch:
        description: "Branch to deploy"
        required: true
        default: "dev"
        type: string
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Extract workflow dispatch inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Extracting workflow dispatch inputs..."
          echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Extract repository dispatch payload
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Extracting payload..."
          echo "BRANCH_NAME=${{ github.event.client_payload.branch_name }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_NAME=${{ github.event.client_payload.image_tag_name }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.SERVER_IP_SALKO0 }} >> ~/.ssh/known_hosts

      - name: Deploy APP to SERVER
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here

      - name: Deploy DB to SERVER
        run: |
          echo "Deploying database to production..."
          # Add your database deployment commands here

      - name: Notify success
        if: ${{ success() }}
        run: |
          echo "Deployment successful!"
          # Add your notification commands here, e.g., sending a message to Slack or Discord
      - name: Notify failure
        if: ${{ failure() }}
        run: |
          echo "Deployment failed!"
          # Add your failure notification commands here, e.g., sending a message to Slack or Discord
